sudo: false
language: java
jdk:
   - openjdk11
cache:
  directories:
  - $HOME/.m2
  - $HOME/apache-maven-3.8.4

## export GPG details
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - export M2_HOME=$HOME/apache-maven-3.8.4
  - if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz | tar zxf - -C $HOME; fi
  - export PATH=$M2_HOME/bin:$PATH

install:
  - mvn --file ikasaneip/pom.xml --settings .settings.xml test -Dmaven.javadoc.skip=true -Djava.security.egd=file:/dev/./urandom -Pall -B -V
#  - if [[ $TRAVIS_BRANCH == "feature/travis-release-IKASAN-1758" ]]; then  mvn --file ikasaneip/pom.xml  clean deploy -Djava.security.egd=file:/dev/./urandom -Pall,release-sign-artifacts -B  -V --settings .settings.xml; fi

## Build and release to maven central
#script:
  ##  mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
#  - if [[ $TRAVIS_BRANCH == "feature/travis-release-IKASAN-1758" ]]; then  mvn --file ikasaneip/pom.xml  clean deploy -Djava.security.egd=file:/dev/./urandom -Pall,release-sign-artifacts -B  -V --settings .settings.xml; fi

deploy:
  # deploy develop 3.2.x to oss
  - provider: script
    script: mvn --file ikasaneip/pom.xml deploy -DskipTests=true -Djava.security.egd=file:/dev/./urandom -Pall -B  -V --settings .settings.xml
    on:
      branch: 3.2.x
  # deploy develop 3.3.x to oss
  - provider: script
    script: mvn --file ikasaneip/pom.xml deploy -DskipTests=true -Djava.security.egd=file:/dev/./urandom -Pall -B  -V --settings .settings.xml
    on:
      branch: 3.3.x
  # deploy scheduler development to oss
  - provider: script
    script: mvn --file ikasaneip/pom.xml deploy -DskipTests=true -Djava.security.egd=file:/dev/./urandom -Pall -B  -V --settings .settings.xml
    on:
      branch: 3.3.x-scheduler-working-branch
  - provider: script
    script: mvn --file ikasaneip/pom.xml deploy -DskipTests=true -Djava.security.egd=file:/dev/./urandom -Pall -B  -V --settings .settings.xml
    on:
      branch: IKASAN-2119_export_import_contexts_core_v1
  # Push release to oss
  - provider: script
    script: mvn --file ikasaneip/pom.xml deploy -DskipTests=true -Djava.security.egd=file:/dev/./urandom -Pall,release-sign-artifacts -B  -V --settings .settings.xml
    on:
      tags: true